{% set name = "typed-settings" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typed-settings-{{ version }}.tar.gz
  sha256: a3470f0ffeff0d2f5a52d2c3035621c4aaf150313b125bf807bce52954ac1494

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - attrs >=22.1
    - cattrs >=22.2
    - python >=3.7
    - tomli >=2  # [py < 311]

test:
  imports:
    - typed_settings
    - typed_settings.attrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/sscherfke/typed-settings
  summary: Typed settings based on attrs classes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
